/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryDuplicatesRouteImport } from './routes/inventory-duplicates'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DataImportRouteImport } from './routes/data-import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as PortalProjectsIndexRouteImport } from './routes/portal/projects/index'
import { Route as PortalScanTokenRouteImport } from './routes/portal/scan/$token'
import { Route as PortalPackageIdRouteImport } from './routes/portal/package/$id'
import { Route as PortalItemIdRouteImport } from './routes/portal/item/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryDuplicatesRoute = InventoryDuplicatesRouteImport.update({
  id: '/inventory-duplicates',
  path: '/inventory-duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DataImportRoute = DataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const PortalProjectsIndexRoute = PortalProjectsIndexRouteImport.update({
  id: '/portal/projects/',
  path: '/portal/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalScanTokenRoute = PortalScanTokenRouteImport.update({
  id: '/portal/scan/$token',
  path: '/portal/scan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPackageIdRoute = PortalPackageIdRouteImport.update({
  id: '/portal/package/$id',
  path: '/portal/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalItemIdRoute = PortalItemIdRouteImport.update({
  id: '/portal/item/$id',
  path: '/portal/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/inventory': typeof InventoryRoute
  '/inventory-duplicates': typeof InventoryDuplicatesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/clients/': typeof ClientsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/portal/item/$id': typeof PortalItemIdRoute
  '/portal/package/$id': typeof PortalPackageIdRoute
  '/portal/scan/$token': typeof PortalScanTokenRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/inventory': typeof InventoryRoute
  '/inventory-duplicates': typeof InventoryDuplicatesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/clients': typeof ClientsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/portal/item/$id': typeof PortalItemIdRoute
  '/portal/package/$id': typeof PortalPackageIdRoute
  '/portal/scan/$token': typeof PortalScanTokenRoute
  '/portal/projects': typeof PortalProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/inventory': typeof InventoryRoute
  '/inventory-duplicates': typeof InventoryDuplicatesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/clients/': typeof ClientsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/portal/item/$id': typeof PortalItemIdRoute
  '/portal/package/$id': typeof PortalPackageIdRoute
  '/portal/scan/$token': typeof PortalScanTokenRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/data-import'
    | '/inventory'
    | '/inventory-duplicates'
    | '/login'
    | '/orders'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/users'
    | '/clients/$clientId'
    | '/orders/$orderId'
    | '/portal/login'
    | '/clients/'
    | '/orders/'
    | '/portal/item/$id'
    | '/portal/package/$id'
    | '/portal/scan/$token'
    | '/portal/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-import'
    | '/inventory'
    | '/inventory-duplicates'
    | '/login'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/users'
    | '/clients/$clientId'
    | '/orders/$orderId'
    | '/portal/login'
    | '/clients'
    | '/orders'
    | '/portal/item/$id'
    | '/portal/package/$id'
    | '/portal/scan/$token'
    | '/portal/projects'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/data-import'
    | '/inventory'
    | '/inventory-duplicates'
    | '/login'
    | '/orders'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/users'
    | '/clients/$clientId'
    | '/orders/$orderId'
    | '/portal/login'
    | '/clients/'
    | '/orders/'
    | '/portal/item/$id'
    | '/portal/package/$id'
    | '/portal/scan/$token'
    | '/portal/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DataImportRoute: typeof DataImportRoute
  InventoryRoute: typeof InventoryRoute
  InventoryDuplicatesRoute: typeof InventoryDuplicatesRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalItemIdRoute: typeof PortalItemIdRoute
  PortalPackageIdRoute: typeof PortalPackageIdRoute
  PortalScanTokenRoute: typeof PortalScanTokenRoute
  PortalProjectsIndexRoute: typeof PortalProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-duplicates': {
      id: '/inventory-duplicates'
      path: '/inventory-duplicates'
      fullPath: '/inventory-duplicates'
      preLoaderRoute: typeof InventoryDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-import': {
      id: '/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof DataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/portal/projects/': {
      id: '/portal/projects/'
      path: '/portal/projects'
      fullPath: '/portal/projects/'
      preLoaderRoute: typeof PortalProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/scan/$token': {
      id: '/portal/scan/$token'
      path: '/portal/scan/$token'
      fullPath: '/portal/scan/$token'
      preLoaderRoute: typeof PortalScanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/package/$id': {
      id: '/portal/package/$id'
      path: '/portal/package/$id'
      fullPath: '/portal/package/$id'
      preLoaderRoute: typeof PortalPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/item/$id': {
      id: '/portal/item/$id'
      path: '/portal/item/$id'
      fullPath: '/portal/item/$id'
      preLoaderRoute: typeof PortalItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DataImportRoute: DataImportRoute,
  InventoryRoute: InventoryRoute,
  InventoryDuplicatesRoute: InventoryDuplicatesRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalItemIdRoute: PortalItemIdRoute,
  PortalPackageIdRoute: PortalPackageIdRoute,
  PortalScanTokenRoute: PortalScanTokenRoute,
  PortalProjectsIndexRoute: PortalProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
